### ISSUE TITLE
Documentation 2.0: Meta task.

### ISSUE THREAD

**Issue by insspb** [cookiecutter/cookiecutter#1409]
Dear users. 

As with release of Cookiecutter 2.0 documentation rework required. We will be glad, if you will find some time to help us with this task.

Master branch version of documentation can be found by latest tag on readthedocs. Direct link is: https://cookiecutter.readthedocs.io/en/latest/cookiecutter.html 

Check related issues to find what should be done.

- [ ] #721 Splitting features of cookiecutter in README
We indeed have some options that required only for developers of templates, some only required to templates users. Splitting seems to be a good idea, but the format is point to discuss.
- [ ] #960 Update troubleshooting documentation.
Currently we have tons of options and troubles can occur in tons of places. This troubles should be described. to begin you can just write some common problems you already faced with cookiecutter.
- [ ] Consider moving [HelloCookieCutter1](https://github.com/BruceEckel/HelloCookieCutter1) repo under [cookiecutter](https://github.com/cookiecutter/)  community. Issue 8 https://github.com/BruceEckel/HelloCookieCutter1/issues/8
- [ ] #1214 Update coding standard

**Comment by insspb** [comment]
Release notes: 
cookiecutter without arguments now display usage+help, not only usage, some commands not require arguments

**Comment by ssbarnea** [comment]
@insspb Please add me (ssbarnea) as maintainer of at https://readthedocs.org/projects/cookiecutter/?badge=latest -- I want to configure native RTD-github integration, where it builds PRs and allow us to browse the result, making much easier to review doc changes. Thanks.
