### ISSUE TITLE
Documentation 2.0: Describe symlinks

### ISSUE THREAD

**Issue by insspb** [cookiecutter/cookiecutter#1420]
Symlinks can make unexpected things with templates developers and templates users. 

So symlinks behaviour should be deeply described and actual defaults should be selected.

Issues and PRs that should be reworked and merged or at least considered:

- [ ] #982 Copy symlinks as symlinks when supported by the platform
- [ ] #865 Symlinks become normal directories when cookiecutter is run
- [ ] #934 Add support for symlinks on posix systems
- [ ] #929 Don't dereference symlinks when using copytree
- [ ] #868 Add support for symlinks in cookiecutter templates

**Comment by dbzm** [comment]
I have to confess I'm somewhat confused as to the "intended" behavior of symlinks.  I see people saying that they don't want them dereferenced when the repo is stamped, which makes sense.

At the same time, however, without symlinks directories become a whole lot less useful.  They're [_called out_](https://cookiecutter.readthedocs.io/en/1.7.2/advanced/directories.html?) in that part of the documentation:
> This allows using symlinks for general files. 

What is the plan for them going forward?

**Comment by SamSchott** [comment]
To chime in on this, I think there are many project structures, especially targeting Unix-like systems, where symlinks play an essential role and should be copied as-is instead of followed. One example are macOS Frameworks which rely on symlinks in their folder structure.

I've just looked through the docs and can see how symlinks are useful to use general files in multiple templates. However, when there is a choice between convenience in setting up the templates (by following symlinks) and not being able to generate a certain type of project at all (projects containing symlinks, relative or absolute), I would probably prefer the versatility in types of projects that can be created.

A good compromise probably is to have a flag / option. My intuition would say that such a flag should default to copying symlinks as-is. But maybe there is an active user base that relies on resolving symlinks...

**Comment by quazzuk** [comment]
Arrgggh! I just followed this

> This allows using symlinks for general files.

symlinked all common files only to find it doesn't work. I agree with the comment above about adding an explicit flag. 

Any plans to add this functionality?

Thanks
AD

**Comment by mforbes** [comment]
@seanh I agree that there should be a flag that allows the current behaviour to be maintained (probably by default), but it would be really nice if there was some way for template manager to be able to use symlinks as symlinks where they make sense.  As I discuss in https://github.com/cookiecutter/cookiecutter/issues/865#issuecomment-1019760635, I can *almost* do this now with a [post-generate hook](https://cookiecutter.readthedocs.io/en/stable/advanced/hooks.html), but this requres hard-coding them in the hook (or in the template).  Can someone more knowledgable comment if there might be some way to use a [pre-generate hook](https://cookiecutter.readthedocs.io/en/stable/advanced/hooks.html) to detect these and pass the information along to cookiecutter so they can be generated by the post-generate hook? (Or tell me if this is not easily doable because there is no way to scan the original template first if running on a platform that does not support symlinks, etc.)

An alternative might be to only preserve in-tree symlinks, but this is clever/tricky and would probably be a pain to maintain.
